apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wine-niagara
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: wine-niagara
    spec:
      containers:
      - name: wine-niagara
        image: gcr.io/radical-sloth/wine-niagara
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 60
      tolerations:
      - key: "preemptible"
        operator: "Exists"
        effect: "NoSchedule"
